# Generated by Django 3.2 on 2022-02-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_total',
        ),
    ]
