# Generated by Django 3.2 on 2022-02-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everest', '0002_remove_purchaseorder_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
