# Generated by Django 3.2 on 2022-02-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everest', '0003_auto_20220208_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
